### PR TITLE
Change license to Apache 2.0

### PR DESCRIPTION
**Pull request by johnsca**

### CODE REVIEW

**Comment by johnsca** [comment]
+1 from me as a contributor (obviously).

**Comment by ChrisMacNaughton** [comment]
+1 from me as a contributor

**Comment by johnsca** [comment]
@tvansteenburgh @bcsaller @stub42 @marcoceppi @mbruzek @jamesbeedy @ChrisMacNaughton please also provide your +1 if you're ok with this change.

**Comment by kwmonroe** [comment]
+1

**Comment by bcsaller** [comment]
+1

**Comment by tvansteenburgh** [comment]
+1

**Comment by stub42** [comment]
+1 from me (erm... wasn't this all work for Canonical, and our approval irrelevant?)

**Comment by ChrisMacNaughton** [comment]
I suspect so...if we can get the legal entity that is Canonical to weigh in :wink:

**Comment by johnsca** [comment]
@stub42 I was asked to ping all contributors, to be safe.  :)  But you're right, if we can get @jamesbeedy to give his +1, I think that would be sufficient.

**Comment by mbruzek** [comment]
+1 from me.

**Comment by jamesbeedy** [comment]
+1

**Pull request merged**
