### PR TITLE
Fix broken pip due to downgrade on Focal+

### LINKED ISSUE #159: venv ends up in a broken state on focal
Focal includes a newer version of pip than we're bundling (20.0.2 vs 18.1) and [the bootstrap logic](https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/basic.py#L178-L179) ends up downgrading it in the venv.  This is succeeds during the `install` hook, but on the first `upgrade-charm` hook it fails with:

```python-traceback
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flannel-0/.venv/bin/pip", line 5, in <module>
    from pip._internal import main
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 23, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.8/site-packages/pip/_internal/index/__init__.py)
```

Since the bundled pip (and setuptools) was there to work around an upstream pip bug due to bionic and below bundling pip < 10, we should just ignore the bundled pip when deploying on focal and above.

### PR DESCRIPTION
**Pull request by johnsca**
Focal provides a newer version of pip (and setuptools) than what is bundled, and downgrading it in the venv leads to it being broken. This doesn't show until after the first bootstrap, so it fails on the first `upgrade-charm` hook rather than the `install` hook. This skips installing pip and setuptools if pip is already at a newer version in the venv.

Fixes #159

### CODE REVIEW

**Comment by johnsca** [comment]
Tested with the ubuntu charm on trusty, xenial, bionic, and focal, with a forced upgrade on each of them:

```
Model  Controller  Cloud/Region   Version  SLA          Timestamp
test   aws         aws/us-east-1  2.7.4    unsupported  13:21:55-04:00

App            Version  Status  Scale  Charm   Store  Rev  OS      Notes
ubuntu-bionic  18.04    active      1  ubuntu  local    1  ubuntu  
ubuntu-focal   20.04    active      1  ubuntu  local    1  ubuntu  
ubuntu-trusty  14.04    active      1  ubuntu  local    1  ubuntu  
ubuntu-xenial  16.04    active      1  ubuntu  local    1  ubuntu  

Unit              Workload  Agent  Machine  Public address  Ports  Message
ubuntu-bionic/0*  active    idle   2        52.206.243.195         ready
ubuntu-focal/0*   active    idle   3        3.231.206.126          ready
ubuntu-trusty/0*  active    idle   0        3.86.92.35             ready
ubuntu-xenial/0*  active    idle   1        34.234.65.54           ready

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  3.86.92.35      i-0fc8ee89ad1e154d2  trusty  us-east-1a  running
1        started  34.234.65.54    i-0ff7c58f88d1dc177  xenial  us-east-1b  running
2        started  52.206.243.195  i-06a4ca79e3fdb1142  bionic  us-east-1c  running
3        started  3.231.206.126   i-009afd6cc6047bd82  focal   us-east-1d  running
```

**Comment by johnsca** [comment]
We might want to consider wrapping some of the Travis steps in folds, as mentioned [here](https://github.com/travis-ci/travis-ci/issues/2285#issuecomment-42724719).

**Comment by fnordahl** [comment]
> We might want to consider wrapping some of the Travis steps in folds, as mentioned [here](https://github.com/travis-ci/travis-ci/issues/2285#issuecomment-42724719)

That looks like a cool feature of Travis indeed.  Note that the main reason for the super-verbose output is to avoid the Travis timeout detection to kick in on days where their clouds are too busy.

So we might also be able to make the output more pleasant if we figure out a way to either extend the timeout or periodically print something to avoid the job timing out while waiting for deplopyment to complete.

**Comment by johnsca** [comment]
@fnordahl The built-in [`travis_wait <cmd>`](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) does the latter.  It's probably worth looking in to because there's also the issue that the output can be [too long and Travis will kill the build anyway](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded).

I'll open an issue about this.

**Pull request merged**
